internal/handler/commands/say.go

Ok friends lets see if this one works better?

Added help to say command.

---

internal/handler/command-handler.go
internal/handler/commands/commands.go
internal/handler/handler.go

This refactors the handler and command-handler to organize things a bit better to make it easier to add in games to the mix

Refactor to make room for games

---

internal/handler/commands/say.go

I expanded the detail in the help message to have examples for same channel.

Added more detail to the help

---

internal/mmclient/mmclient.go

Fixes the bug where the bot status always shows away

Set status to online

---

internal/handler/game-handler.go
internal/handler/games/games.go
internal/handler/games/help.go
internal/handler/handler.go

Adds in handler logic to run games. It'll probably need to be tweaked, but it's a start.
It basically extends the same functionality to the `$` trigger that `!` offers for commands.

New games handler

---

internal/handler/command-handler.go
internal/handler/commands/commands.go
internal/handler/commands/joke.go

New joke command

---

daemon/daemon.go
internal/handler/games/rps.go

fix dm bug

---

go.mod
go.sum
internal/handler/games/tictactoe/README.md
internal/handler/games/tictactoe/bgn.go
internal/handler/games/tictactoe/builder.go
internal/handler/games/tictactoe/models.go
internal/handler/games/tictactoe/state.go
internal/handler/games/tictactoe/tictactoe.go
internal/handler/games/ttt.go

This adds code for a game of Tic Tac Toe

New Tic Tac Toe game

---

docker-compose.yaml
internal/comms/comms.go
internal/handler/command-handler.go
internal/handler/commands/apb.go
internal/handler/commands/caffeine.go
internal/handler/commands/commands.go
internal/handler/commands/emote.go
internal/handler/commands/help.go
internal/handler/commands/insult.go
internal/handler/commands/joke.go
internal/handler/commands/message.go
internal/handler/commands/praise.go
internal/handler/commands/quote.go
internal/handler/commands/react.go
internal/handler/commands/reload.go
internal/handler/commands/roll.go
internal/handler/commands/s.go
internal/handler/commands/say.go
internal/handler/commands/thought.go
internal/handler/game-handler.go
internal/handler/games/games.go
internal/handler/games/help.go
internal/handler/games/rps.go
internal/handler/games/ttt.go
internal/handler/handler.go
internal/mmclient/mmclient.go

This is still in progress. I am working to make the games use a channel for messages so we don't have to do silly string manipulation.

Created routine for writing messages to channels for games.

---

internal/comms/comms.go
internal/handler/games/farkle.go
internal/handler/games/games.go
internal/handler/games/help.go
internal/handler/games/rps.go
internal/handler/games/rps/rps-funtions.go
internal/handler/games/ttt.go
internal/handler/games/wh.go

Realizing that many games may require similarly named functions, I refactored the RPS game to use functions contained within its own package.

Creates a separate package for RPS functions.

---

internal/handler/command-handler.go

Cross channel communications were broken by implementation of channels to do multi-message communications.

Fixes cross channel communications. 

---

internal/comms/comms.go

The posts for DMs were showing the command, for instance one might see the `/echo` prefix.

Fixes the say command for DMs.

---

internal/comms/comms.go

Reverts PyrousNET/pyrous-gobot#43

Revert "Fixes the say command for DMs."

---

internal/comms/comms.go

Reverts PyrousNET/pyrous-gobot#44

Revert "Revert "Fixes the say command for DMs.""

---

internal/comms/comms.go
spells.json

This was a permissions problem because we didn't not include the bot's team id.

🐛 Fixed a bug with the `!emote` command.

---

internal/comms/comms.go

This should prevent unintented shutdown.

🥅 Removes panic from error handling

---

internal/handler/commands/remindme.go

Changed parser and responded to remindme request

🐛 Fixed issue when separator shows up more than once.

---

reactions.json

Adds an extra creepy lenny face.

Adds the creepy lenny face

---

internal/handler/commands/react.go

This uses markdown to caption the gif with the description.

Fixes reactions so you don't see the url

---

reactions.json

add koby reaction

---

.github/workflows/go.yml
internal/handler/commands/react_test.go
internal/handler/games/wh.go
internal/handler/games/wh_test.go
internal/settings/settings.go

This PR adds a github workflow for running tests on the branches which are staged as pull requests.

Adds github workflow to run tests

---

daemon/daemon.go
reactions.json

I got the daemon to work after this change.

Use the proper relative directory for daemon

---

go.mod
go.sum

Upgrades packages to fix vulnerabilities

---

go.mod
go.sum

chore: upgrade mattermost-server library

---

reactions.json

Update reactions.json - Added lol-yikes
